### ISSUE TITLE
Major performance degradation after period of use

### ISSUE THREAD

**Issue by lesderid** [maharmstone/btrfs#346]
I've been using WinBtrfs for the past couple weeks on my secondary disk, mainly for Steam games and file sharing (both sequential and random-access, both small files and large files).

Since I've started using it, I've been experiencing regular deadlocks, or at the very least major performance degradation, every so often, causing e.g. Windows Explorer to stop responding. The only 'fix' has been to hard reboot when it happens. It seems to happen whether there's a pagefile on the volume or not.

WinBtrfs version is 1.7.6, Windows 8.1 (latest build). Compression is enabled, but not forced, algorithm is zstd (default level), no other configuration changes. File system was formatted with mkbtrfs.exe. Hasn't bugchecked.

Possible duplicate of #58, #338, #345

**Comment by lesderid** [comment]
I tried collecting some data for debugging by copying (with `COPY /B` in a batch file) a 4GiB file with random data from NTFS to Btrfs on a Hyper-V VM. The guest has two disks, backed by files on the same NTFS HDD, one formatted as NTFS and one formatted with `mkbtrfs.exe` right before testing.

Guest (and host) running clean Windows 8.1 x64, with most inessential Windows services disabled, and Driver Verifier enabled with standard settings. I'm using a debug build of 04da8409ca7b56d809437d61db2f5a1a566f451a (with some logging changes). A release build with logging disabled didn't seem to make a difference.

WinBtrfs logs (split for easier viewing/filtering): https://files.lesderid.net/btrfs-windbg-logs.0.tar.gz

Locks: https://pst.moe/paste/oiwnoy

It looks like it starts writing in 1MiB byte chunks and then slows down to 4KiB chunks and occasionally stalls? Running the second log file through `uniq -D | uniq -c`:

```
  62177 [btrfs] FFFFE00046751040:fast_io_acquire_for_mod_write:C:\Users\lesderid\msys\repos\winbtrfs\src\fastio.c:275:(FFFFE00048BF8470, b74fd000, FFFFE00048A22DB8, FFFFE00048F64030)
 124048 [btrfs] FFFFE00046751040:fast_io_acquire_for_mod_write:C:\Users\lesderid\msys\repos\winbtrfs\src\fastio.c:275:(FFFFE00048BF8470, b7dc9000, FFFFE00048EF0608, FFFFE00048F64030)
 134375 [btrfs] FFFFE00046751040:fast_io_acquire_for_mod_write:C:\Users\lesderid\msys\repos\winbtrfs\src\fastio.c:275:(FFFFE00048BF8470, b9760000, FFFFE00048EF0608, FFFFE00048F64030)
 144459 [btrfs] FFFFE00046751040:fast_io_acquire_for_mod_write:C:\Users\lesderid\msys\repos\winbtrfs\src\fastio.c:275:(FFFFE00048BF8470, b9e24000, FFFFE00048EF0608, FFFFE00048F64030)
 143159 [btrfs] FFFFE00046751040:fast_io_acquire_for_mod_write:C:\Users\lesderid\msys\repos\winbtrfs\src\fastio.c:275:(FFFFE00048BF8470, aa9c9000, FFFFE00048EF0608, FFFFE00048F64030)
  18872 [btrfs] FFFFE00046751040:fast_io_acquire_for_mod_write:C:\Users\lesderid\msys\repos\winbtrfs\src\fastio.c:275:(FFFFE00048BF8470, aae77000, FFFFE00048EF0608, FFFFE00048F64030)
```

The behaviour seems to be a little different (maybe due to caching on the host or something) from a real machine, but there's clearly still something that's going wrong.

**Comment by maharmstone** [comment]
Thanks @lesderid, that's very useful. Could you try against 2818f989deeaa1ae13014fa857cc489e6dc81f64, and see if it's any better?

**Comment by lesderid** [comment]
> Thanks @lesderid, that's very useful. Could you try against [2818f98](https://github.com/maharmstone/btrfs/commit/2818f989deeaa1ae13014fa857cc489e6dc81f64), and see if it's any better?

No problem. That seems to have fixed it!

**Comment by szaimen** [comment]
I've just experienced the same issue last night but installed v1.7.7 and can gladly report that it fixes the issue :)

**Comment by lesderid** [comment]
I'm afraid it isn't completely fixed for me, I came back to a deadlocked system after running some IO intensive workloads overnight. I'll try to investigate.

**Comment by lesderid** [comment]
I think the problem might be that `fast_io_acquire_for_ccflush`/`fast_io_release_for_ccflush` don't do what they ought to do.  Unlinking them from the FastIO dispatch (so it falls back to a default implementation) seems to work, but I'm not sure that's correct, and I don't know how I can consistently reproduce this.

**Comment by RigoLigoRLC** [comment]
I'm afraid that I'm experiencing the same issue.

On my PC I have my NTFS drive C (230GB) and Btrfs drive D (700GB with 4 subvolumes). All partitions are on a high performance NVMe SSD. If I perform some IO intensive task on Btrfs volume (like compiling a large C++ project) the system will become gradually unresponsive. Mouse can move but the UI stopped processing clicking and hovering events, and the applications are not being blocked and are still running fine (for example, Discord in Firefox can still receive messages). When the compilation ends, the clicking events that were created during the hang will all be processed. But Windows UI performance will not restore and UI is going to be less responsive, and keep degrading over time. If I close the laptop lid the system sleeps normally, but usually won't wake up to LogonUI anymore, leaving a blue background with a mouse cursor.

System info: Windows 10 Pro 19043.1110 (21H1)
Winbtrfs: 1.7.9

**Comment by kwencel** [comment]
@RigoLigoRLC what you are describing seems more like [this](https://github.com/maharmstone/btrfs/issues/438). However, they all might be related.

**Comment by lesderid** [comment]
Has this been fixed (since April 2021)? I haven't been using WinBtrfs since then because of the instability.

I've been trying to reproduce it now in a clean WinPE environment and so far I haven't run into it, but I've never been able to reproduce this very reliably.

**Comment by Small-Ku** [comment]
I am facing the deadlock when I am playing Honkai: Star Rails.
```
Possible deadlock. Use !locks FFFF8A083BF07378 to determine the resource owner
DBGK: DbgkWerCaptureLiveKernelDump: WerLiveKernelCreateReport failed, status 0xc0000099.
``` 
DebugView seems show some log like this but I don't know what can be done further with the provided command in this log.

**Comment by sumariva** [comment]
OK. I will try help you reproduce the problem of slow performance.
Go to the https://www.getmonero.org/downloads/#gui! Yes, it is me again with the crypto things.
Get the monero GUI client for windows and install it. 
During install process, the Microsoft Windows Defender may warn of virus, tell it to ignore the files.
Add the monero folder to the user/system path, sou that you can access the monero binaries easily from the command prompt.

Have an btrfs partition with some space available, and compression DISABLED.
Start the monero client to begin synchronization like this, it will create the folder, if it does not exists on target:
`monerod --data-dir=e:\monero --prune-blockchain --out-peers=128`

To stop monerod, hit Ctrl+C, to issue an EOF(end of file) char to the input of monerod.
You will also notice a long time the monerod needs to wait for I/O on his finalization process.
The monerod takes several minutes to finish waiting I/O.

Monero will be a great tool to help you with IO issues. It will log messages to the console, it is I/O intensive and very stable.
It uses two files at a folder called lmdb. The data.mdb will grow up to 65GiB.

I started the sync process on a NTFS partition. I let it sync up to 99%. It took about 24h with a 20megabit Internet link.
I got out of space when sync reached 99%. So, I moved the large file to the brtfs.

But now, to my surprise, it took one day to sync 400 blocks, due to slow performance on btrfs.
Now, I upgraded to the last version 1.9.0 but the issue is still there.
I hope I provided you with a good test case.
I will attach some screen captures from version 1.8.2. But after the upgrade, the same slow thing is happening.
When it was on NTFS, the disk activity, was about 30MiB/s, and disk usage about 100%.

Now on the btrfs, the disk activity is lagging, almost no internet use, since monerod blocked waiting I/O to finish.
![btrfswin-issue-slow-update](https://github.com/maharmstone/btrfs/assets/6371372/b449380d-9afd-4004-8069-4b59d56fee86)
See the last modification time at windows explorer. And the system process eating one CPU thread.

![btrfswin-issue-slow-update-monerod-iounlocked](https://github.com/maharmstone/btrfs/assets/6371372/d7632ae6-479f-4aea-87cc-82b2df47edff)
Between 5 to 15minutes later, the system process finish the flush of data and unlocks, so the OS push monerod to execution again. And a few seconds later, the OS locks it again and the system process begins to eat the CPU again.

Reproducible: always.
To restart the sync from beggining, just delete the *.mdb files.

Maybe some issue related to the FAM(File Alteration Monitor).
Hope it helps you with input data, for test case!
Monerod also have options to choose the number of threads, in case you want CPU stress with I/O!

**Comment by maharmstone** [comment]
Thanks, I'll give it a go.

These MDB files look like databases to me - possibly the solution is to set the nocow flag on the directory. Databases don't play well with copy-on-write, on any OS.

**Comment by sumariva** [comment]
I forget to tell you, Windows Explorer also freeze while waiting I/O.
The target system is a Windows 10 x64, on an Intel I3 1.8ghz, notebook, on A/C adapter, adicted/faulty battery.
The machine has been rebooted to load 1.9.0.

![btrfswin-slow-nocow](https://github.com/maharmstone/btrfs/assets/6371372/4e8012a3-7ef6-4d7c-845e-fdca0a68efff)
Activated nocow, stopped and restarted monerod, since I do not know if these nocow has something related with open file descriptors on already running process.
But the 25%, I guess a process/thread loaded keeps going on.

**Comment by musabagriyanik** [comment]
I'm experiencing an issue that looks similar to that, after quitting a Steam game installed on a BTRFS drive, Steam becomes unresponsive, Steam itself is installed in C drive which is NTFS. The UI works, but buttons don’t do anything, and I can’t close the app. When I try to kill the Steam processes, one of them (steam.exe) won’t terminate, and Task Manager gives an "Access Denied" error, even though it’s running under my user account. I suspect the BTRFS driver is interfering with this, because in File Explorer, the BTRFS drive doesn’t show its size bar, only the label and drive letter are visible. I also can't open and view contents of the drive in Explorer. This all happens until I reboot, but it's happening regularly.

I don't think this has anything to do with Steam, similar deadlocks happened before when just viewing the drive with File Explorer. Where File Explorer window stuck on the screen and can't be killed in Task Manager, you see two explorer.exe there and while one gets closed, which is taskbar and window manager, the one that stuck doesn't terminate, exact problem with steam.exe

**Comment by s-mayrh** [comment]
I also have seen "System" having high CPU usage as well while using the **Signal desktop** client. The program gets locked up (waiting for IO) every few seconds but there are no operations on the drive according to task manager during lockups, but task manager shows CPU usage being entirely within kernel space and I think this is some computation within the WinBtrfs driver.

I symlinked both Signal's data and program dirs from the user `AppData` directories to a BTRFS drive.

**Comment by virtuous-byte** [comment]
I'm experiencing this issue as well, it essentially happens while writing data to disk. One and easy to reproduce case I had is Steam downloading a game to the BTRFS partition, Steam shows you the network bandwidth and disk utilization pretty well, you can see that disk utilization is going to 0 b/sn as well as network bandwidth. This is because Steam downloads files in parts and it doesn't keep downloading new part before the previous parts are written to the drive, but it's unable to write. When this happens you can run explorer.exe, and check the drives status. BTRFS partition will not show disk usage bar and any information except the label and drive letter.

**Comment by darkjezza** [comment]
So I think I'm experiencing the same problem when I'm transferring games from one drive to the BTRFS drive in steam my BTRFS drive will stop responding.

**Comment by namquang93** [comment]
I got the same issue.

**Comment by ISNing** [comment]
After experiencing repeated system freezes resolvable only through hard resets, I observed consistent recurrence during large file downloads (potentially specific to storage-preallocating applications). This coincides with severe disk performance degradation, particularly in random 4K write operations:

https://github.com/user-attachments/assets/ad05ac27-8bdd-483e-8def-846f461fbd39

Note: While applying the NOCOW attribute initially boosted performance metrics significantly, it proved ineffective in mitigating performance degrading issues. I can't logout or power off the system, it stucks at "Logging off..." screen and if I hard reset the device, it may breaks some file.

In my case, while downloading Honkai: StarRail through Collapse Launcher(https://github.com/CollapseLauncher/Collapse), the transfer rate exhibited progressive degradation from 100MB/s to 2.xMB/s before ultimately failing with write errors. Subsequent deletion of temporary files allowed the download process to restart, but merely replicated the deterioration pattern. Notably, system freezing didn't occur sometimes.

**Comment by shishimaru90** [comment]
> After experiencing repeated system freezes resolvable only through hard resets, I observed consistent recurrence during large file downloads (potentially specific to storage-preallocating applications). This coincides with severe disk performance degradation, particularly in random 4K write operations:
> 
> ![Image](https://github.com/user-attachments/assets/ad05ac27-8bdd-483e-8def-846f461fbd39)
> 
> Note: While applying the NOCOW attribute initially boosted performance metrics significantly, it proved ineffective in mitigating performance degrading issues. I can't logout or power off the system, it stucks at "Logging off..." screen and if I hard reset the device, it may breaks some file.
> 
> In my case, while downloading Honkai: StarRail through Collapse Launcher(https://github.com/CollapseLauncher/Collapse), the transfer rate exhibited progressive degradation from 100MB/s to 2.xMB/s before ultimately failing with write errors. Subsequent deletion of temporary files allowed the download process to restart, but merely replicated the deterioration pattern. Notably, system freezing didn't occur sometimes. The Collapse Launcher says:
> 
> ```
> System.IO.IOException: 请求的操作无法在使用用户映射区域打开的文件上执行。 (Translated: The requested operation cannot be performed on a file that is opened using the user mapping area.): 'E:\blabla\StarRail\game_3.2.0_3.3.0_hdiff_rfUEDALxLKoRInYi.7z.collapseMeta'.
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at Hi3Helper.Http.Metadata.SaveLastMetadataStateAsync(CancellationToken token)
>    at Hi3Helper.Http.Metadata.SaveLastMetadataStateAsync(CancellationToken token)
>    at Hi3Helper.Http.DownloadClient.PerformDownloadWriteDelegate(DownloadProgressDelegate progressDelegateAsync, Int32 maxConnectionSessions, DownloadSpeedLimiter downloadSpeedLimiter, ChunkSession chunk, FileStreamOptions fileStreamOptions, DownloadProgress downloadProgressStruct, CancellationToken cancelToken)
>    at Hi3Helper.Http.DownloadClient.PerformDownloadWriteDelegate(DownloadProgressDelegate progressDelegateAsync, Int32 maxConnectionSessions, DownloadSpeedLimiter downloadSpeedLimiter, ChunkSession chunk, FileStreamOptions fileStreamOptions, DownloadProgress downloadProgressStruct, CancellationToken cancelToken)
>    at Hi3Helper.Http.DownloadClient.<>c__DisplayClass23_0.<<DownloadAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__57`1.<<ForEachAsync>b__57_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Hi3Helper.Http.DownloadClient.DownloadAsync(String url, FileInfo fileOutputPath, Boolean useOverwrite, Nullable`1 offsetStart, Nullable`1 offsetEnd, DownloadProgressDelegate progressDelegateAsync, Int32 maxConnectionSessions, Int32 sessionChunkSize, DownloadSpeedLimiter downloadSpeedLimiter, CancellationToken cancelToken)
>    at CollapseLauncher.Interfaces.ProgressBase`1.RunDownloadTask(Int64 assetSize, FileInfo assetPath, String assetURL, String secondaryURL, DownloadClient downloadClient, DownloadProgressDelegate downloadProgress, CancellationToken token, Boolean isOverwrite)
>    at CollapseLauncher.InstallManager.Base.InstallManagerBase.RunPackageDownloadRoutine(Http httpClient, DownloadClient downloadClient, GameInstallPackage package, Int32 packageCount, CancellationToken token)
>    at CollapseLauncher.InstallManager.Base.InstallManagerBase.InvokePackageDownloadRoutine(DownloadClient downloadClient, List`1 packageList, CancellationToken token)
>    at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageDownload(Boolean skipDialog)
>    at CollapseLauncher.Pages.HomePage.PredownloadDialog(Object sender, RoutedEventArgs e)
> ```
> 
> When writing into btrfs partitions, the explorer says: `The disk is write-protected`
> 
> P.S. No errors found by scrub:
> 
> ![Image](https://github.com/user-attachments/assets/12b21b68-f151-4331-8ab5-9c2c778f7681)

Same issue here, and I've redone everything with CoW enabled. Truly scared to disable it now. That performance boost at the beginning isn't worth the huge loss of stability. Compression with low level LZO helps a super little bit with 4k random writes, but I'm not even 100% sure.

**Comment by lesderid** [comment]
I'm closing this, it seems very likely this is fixed by https://github.com/maharmstone/btrfs/pull/753.

**Comment by szaimen** [comment]
Thanks a lot! Would it be possible to create a new release that ships this fix? :)
